# Da Api Client
da_api_client:
    api:
        media:
            endpoint_root: %media_http_client_endpoint_root%
            cache_enabled: true

twig:
    form:
        resources:
            - 'TmsMediaClientBundle:Form:fields.html.twig'
