# Da Api Client
da_api_client:
    api:
        media:
            endpoint_root: %api.media.endpoint_root%
            security_token: %api.security_token%
            cache_enabled: true

twig:
    form:
        resources:
            - 'TmsMediaClientBundle:Form:fields.html.twig'
