services:
    tms_media_client.manager:
        class: Tms\Bundle\MediaClientBundle\Manager\MediaClientManager
        arguments: [@da_api_client.api.media]

    form.type.media:
        class: Tms\Bundle\MediaClientBundle\Form\Type\MediaType
        arguments: [@tms_media_client.manager]
        tags:
            - { name: form.type, alias: media }

    tms_media_client.twig.website_extension:
        class: Tms\Bundle\MediaClientBundle\Twig\MediaExtension
        arguments: [@tms_media_client.manager]
        tags:
            - { name: twig.extension }
